### ISSUE TITLE
Antsibull-docs not outputting any files or out putting anything in console

### ISSUE THREAD

**Issue by s0r3-glitch** [ansible-community/antsibull-docs#5]
Well trying to get antsibull to generate a RST file for my collection, I have encountered an issue where nothing is getting output to the console or to a file in the build directory I specified in the command. There doesn't seem to be an option to enable debugging for the command, and I am unsure what the problem is. Does anyone know what I can do to get more information in the console or to find out why it's not making a file?

**Comment by felixfontein** [comment]
You can create a `~/.antsibull.cfg` file and configure logging there. The following shows how this works: https://github.com/ansible-community/antsibull-core/blob/main/antsibull.cfg#L29-L56 (I have to admit that I never tried increasing verbosity yet, I simply add `print()` statements when I need them :) )

In any case, what's the command line you're using? Maybe seeing it allows me to give you a hint where to look already.

**Comment by s0r3-glitch** [comment]
`antsibull-docs collection --use-current --squash-hierarchy --dest-dir ./build/plugin_docs test.test`
I will try out the the antsibull config and see try it again

**Comment by s0r3-glitch** [comment]
So I set up the logging in the antsibull config file and set the logging level to debug but everything seems normal on in it

**Comment by felixfontein** [comment]
Hmm, what happens if you run `ansible-doc --list test.test` (assuming the collection has modules)? Do you see something? I.e. did you set up `COLLECTIONS_PATHS` correctly so that the collection is found by Ansible?

**Comment by s0r3-glitch** [comment]
Sorry for getting back late, It appears as if the collection isn't actually listed in `ansible-doc --list` going to get that fixed and try again

**Comment by s0r3-glitch** [comment]
decided to try and use a collection that ansible recognized and now I am getting this error
`Traceback (most recent call last):
  File "/usr/local/bin/antsibull-docs", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/antsibull_docs/cli/antsibull_docs.py", line 450, in main
    return run(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/antsibull_docs/cli/antsibull_docs.py", line 431, in run
    return ARGS_MAP[args.command]()
  File "/usr/local/lib/python3.9/site-packages/antsibull_docs/cli/doc_commands/collection.py", line 112, in generate_docs
    return generate_collection_docs(None, squash_hierarchy)
  File "/usr/local/lib/python3.9/site-packages/antsibull_docs/cli/doc_commands/collection.py", line 40, in generate_collection_docs
    return generate_docs_for_all_collections(
  File "/usr/local/lib/python3.9/site-packages/antsibull_docs/cli/doc_commands/stable.py", line 325, in generate_docs_for_all_collections
    plugin_info, collection_metadata = asyncio_run(get_ansible_plugin_info(
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/antsibull_docs/docs_parsing/parsing.py", line 71, in get_ansible_plugin_info
    return await ansible_internal_get_ansible_plugin_info(
  File "/usr/local/lib/python3.9/site-packages/antsibull_docs/docs_parsing/ansible_internal.py", line 63, in get_ansible_plugin_info
    collection_enum_cmd = venv_python(*collection_enum_args, _env=env)
  File "/usr/local/lib/python3.9/site-packages/sh.py", line 1566, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/usr/local/lib/python3.9/site-packages/sh.py", line 822, in __init__
    self.wait()
  File "/usr/local/lib/python3.9/site-packages/sh.py", line 879, in wait
    self.handle_command_exit_code(exit_code)
  File "/usr/local/lib/python3.9/site-packages/sh.py", line 905, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/local/bin/python /tmp/tmptrj9ilan ovirt.ovirt.ovirt_vm

  STDOUT:


  STDERR:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/ansible/collections/list.py", line 63, in list_collection_dirs
    (namespace, collection) = coll_filter.split('.')
ValueError: too many values to unpack (expected 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/tmptrj9ilan", line 261, in <module>
    main(sys.argv)
  File "/tmp/tmptrj9ilan", line 234, in main
    result['plugins'][plugin_type] = load_all_plugins(plugin_type, basedir, coll_filter)
  File "/tmp/tmptrj9ilan", line 125, in load_all_plugins
    doc.add_collection_plugins(
  File "/usr/local/lib/python3.9/site-packages/ansible/cli/doc.py", line 67, in add_collection_plugins
  ... (305 more, please see e.stderr)`

**Comment by felixfontein** [comment]
Which collection did you provide? Did you provide `ovirt.ovirt.ovirt_vm`? (That's not a collection name.)

**Comment by s0r3-glitch** [comment]
So I gave it a try with `ovirt.ovirt` and it worked properly, guess the issue with this whole thing was that my collection wasnt being registered properly so i guess i got to figure that out now. Thank you for helping.

**Comment by felixfontein** [comment]
You're welcome and good luck!
